### ISSUE TITLE
Docker For Windows

### ISSUE THREAD

**Issue by TheStormN** [jgregmac/hyperv-fix-for-devs#7]
The fix works well for WSL, but Docker for Windows does install more Hyper-V adapters which are clashing with the VPN network on which I'm located. The script does not work for the docker generated Hyper-V adapters...

**Comment by jgregmac** [comment]
I am sorry, addressing the Docker Desktop networks is out-of-scope for this project.  Part of why I was so intent on getting this solution working was so that I could run Kubernetes, Podman, or even Docker natively in my WSL environment and not have to worry about what crazy stuff the Docker Desktop tool is trying to do to my system.

I am working primarily on container environments running on Kubernetes.  You can use this solution to run Microk8s or Minikube in WSL, but I also use Podman quite a lot for quick container builds and validation.
